import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The sidebar is generated from the docs/ folder structure. Add a `sidebar_position`
 * to a page's front matter, or a `_category_.json` to a folder, to control ordering;
 * switch to an explicit item list here if the tree ever needs hand-curation.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
